# port
server:
  port: 8080

# Oracle DB
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: assignment
    password: assignment

# Thymeleaf
spring:
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:templates/
    suffix: .html

# MyBatis
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  type-aliases-package: "com.yangworld.app, org.springframework.security.core.authority"
  type-handlers-package: "com.yangworld.app.common.typehandler"
  mapper-locations: "classpath*:mapper/**/*-mapper.xml"


riot:
  api-key: 12345
